export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_INFO = "AUTH_INFO";

export const FETCH_PRODUCTS_START = "FETCH_PRODUCTS_START";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAIL = "FETCH_PRODUCTS_FAIL";
export const ADD_PRODUCT_START = "ADD_PRODUCT_START";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";
export const ADD_PRODUCT_HANDLER = "ADD_PRODUCT_HANDLER";
export const CANCEL_ADD_HANDLER = "CANCEL_ADD_HANDLER";
export const CANCEL_MESSAGE_HANDLER = "CANCEL_MESSAGE_HANDLER";

export const FETCH_PROD_START = "FETCH_PROD_START";
export const FETCH_PROD_SUCCESS = "FETCH_PROD_SUCCESS";
export const FETCH_PROD_FAIL = "FETCH_PROD_FAIL";
export const DELETE_PROD_START = "DELETE_PROD_HANDLER";
export const DELETE_PROD_SUCCESS = "DELETE_PROD_SUCCESS";
export const DELETE_PROD_FAIL = "DELETE_PROD_FAIL";
export const ADD_TO_CART = "ADD_TO_CART";
export const EDIT_PROD_HANDLER = "EDIT_PROD_HANDLER";
export const OPEN_MESSAGE = "OPEN_MESSAGE";
export const PROD_CANCEL_MESSAGE_HANDLER = "PROD_CANCEL_MESSAGE_HANDLER";
export const EDIT_PROD_START = "EDIT_PROD_START";
export const EDIT_PROD_SUCCESS = "EDIT_PROD_SUCCESS";
export const EDIT_PROD_FAIL = "EDIT_PROD_FAIL";
export const CANCEL_EDIT_HANDLER = "CANCEL_EDIT_HANDLER";
export const CANCEL_EDIT_MESSAGE = "CANCEL_EDIT_MESSAGE";

export const CREATE_ORDER_START = "CREATE_ORDER_START";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";
export const DELETE_CART_PRODUCT = "DELETE_CART_PRODUCT";
export const ORDER_OPEN_MESSAGE = "ORDER_OPEN_MESSAGE";
export const ORDER_CANCEL_MESSAGE_HANDLER = "ORDER_CANCEL_MESSAGE_HANDLER";

export const FETCH_SALES_START = "FETCH_SALES_START";
export const FETCH_SALES_SUCCESS = "FETCH_SALES_SUCCESS";
export const FETCH_SALES_FAIL = "FETCH_SALES_FAIL";
